// Code generated by go-swagger; DO NOT EDIT.

package stream_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAddStreamParams creates a new AddStreamParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddStreamParams() *AddStreamParams {
	return &AddStreamParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddStreamParamsWithTimeout creates a new AddStreamParams object
// with the ability to set a timeout on a request.
func NewAddStreamParamsWithTimeout(timeout time.Duration) *AddStreamParams {
	return &AddStreamParams{
		timeout: timeout,
	}
}

// NewAddStreamParamsWithContext creates a new AddStreamParams object
// with the ability to set a context for a request.
func NewAddStreamParamsWithContext(ctx context.Context) *AddStreamParams {
	return &AddStreamParams{
		Context: ctx,
	}
}

// NewAddStreamParamsWithHTTPClient creates a new AddStreamParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddStreamParamsWithHTTPClient(client *http.Client) *AddStreamParams {
	return &AddStreamParams{
		HTTPClient: client,
	}
}

/*
AddStreamParams contains all the parameters to send to the API endpoint

	for the add stream operation.

	Typically these are written to a http.Request.
*/
type AddStreamParams struct {

	// Stream.
	Stream AddStreamBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add stream params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddStreamParams) WithDefaults() *AddStreamParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add stream params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddStreamParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add stream params
func (o *AddStreamParams) WithTimeout(timeout time.Duration) *AddStreamParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add stream params
func (o *AddStreamParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add stream params
func (o *AddStreamParams) WithContext(ctx context.Context) *AddStreamParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add stream params
func (o *AddStreamParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add stream params
func (o *AddStreamParams) WithHTTPClient(client *http.Client) *AddStreamParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add stream params
func (o *AddStreamParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithStream adds the stream to the add stream params
func (o *AddStreamParams) WithStream(stream AddStreamBody) *AddStreamParams {
	o.SetStream(stream)
	return o
}

// SetStream adds the stream to the add stream params
func (o *AddStreamParams) SetStream(stream AddStreamBody) {
	o.Stream = stream
}

// WriteToRequest writes these params to a swagger request
func (o *AddStreamParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Stream); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
