// Code generated by go-swagger; DO NOT EDIT.

package recorder_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteRecordingParams creates a new DeleteRecordingParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteRecordingParams() *DeleteRecordingParams {
	return &DeleteRecordingParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteRecordingParamsWithTimeout creates a new DeleteRecordingParams object
// with the ability to set a timeout on a request.
func NewDeleteRecordingParamsWithTimeout(timeout time.Duration) *DeleteRecordingParams {
	return &DeleteRecordingParams{
		timeout: timeout,
	}
}

// NewDeleteRecordingParamsWithContext creates a new DeleteRecordingParams object
// with the ability to set a context for a request.
func NewDeleteRecordingParamsWithContext(ctx context.Context) *DeleteRecordingParams {
	return &DeleteRecordingParams{
		Context: ctx,
	}
}

// NewDeleteRecordingParamsWithHTTPClient creates a new DeleteRecordingParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteRecordingParamsWithHTTPClient(client *http.Client) *DeleteRecordingParams {
	return &DeleteRecordingParams{
		HTTPClient: client,
	}
}

/*
DeleteRecordingParams contains all the parameters to send to the API endpoint

	for the delete recording operation.

	Typically these are written to a http.Request.
*/
type DeleteRecordingParams struct {

	/* ID.

	   Recording ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete recording params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteRecordingParams) WithDefaults() *DeleteRecordingParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete recording params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteRecordingParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete recording params
func (o *DeleteRecordingParams) WithTimeout(timeout time.Duration) *DeleteRecordingParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete recording params
func (o *DeleteRecordingParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete recording params
func (o *DeleteRecordingParams) WithContext(ctx context.Context) *DeleteRecordingParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete recording params
func (o *DeleteRecordingParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete recording params
func (o *DeleteRecordingParams) WithHTTPClient(client *http.Client) *DeleteRecordingParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete recording params
func (o *DeleteRecordingParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete recording params
func (o *DeleteRecordingParams) WithID(id string) *DeleteRecordingParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete recording params
func (o *DeleteRecordingParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteRecordingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
