// Code generated by go-swagger; DO NOT EDIT.

package recorder_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewRecordingControlParams creates a new RecordingControlParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRecordingControlParams() *RecordingControlParams {
	return &RecordingControlParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRecordingControlParamsWithTimeout creates a new RecordingControlParams object
// with the ability to set a timeout on a request.
func NewRecordingControlParamsWithTimeout(timeout time.Duration) *RecordingControlParams {
	return &RecordingControlParams{
		timeout: timeout,
	}
}

// NewRecordingControlParamsWithContext creates a new RecordingControlParams object
// with the ability to set a context for a request.
func NewRecordingControlParamsWithContext(ctx context.Context) *RecordingControlParams {
	return &RecordingControlParams{
		Context: ctx,
	}
}

// NewRecordingControlParamsWithHTTPClient creates a new RecordingControlParams object
// with the ability to set a custom HTTPClient for a request.
func NewRecordingControlParamsWithHTTPClient(client *http.Client) *RecordingControlParams {
	return &RecordingControlParams{
		HTTPClient: client,
	}
}

/*
RecordingControlParams contains all the parameters to send to the API endpoint

	for the recording control operation.

	Typically these are written to a http.Request.
*/
type RecordingControlParams struct {

	/* ID.

	   Recording ID
	*/
	ID string

	/* Pause.

	   Pause/Resume
	*/
	Pause bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the recording control params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RecordingControlParams) WithDefaults() *RecordingControlParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the recording control params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RecordingControlParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the recording control params
func (o *RecordingControlParams) WithTimeout(timeout time.Duration) *RecordingControlParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the recording control params
func (o *RecordingControlParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the recording control params
func (o *RecordingControlParams) WithContext(ctx context.Context) *RecordingControlParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the recording control params
func (o *RecordingControlParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the recording control params
func (o *RecordingControlParams) WithHTTPClient(client *http.Client) *RecordingControlParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the recording control params
func (o *RecordingControlParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the recording control params
func (o *RecordingControlParams) WithID(id string) *RecordingControlParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the recording control params
func (o *RecordingControlParams) SetID(id string) {
	o.ID = id
}

// WithPause adds the pause to the recording control params
func (o *RecordingControlParams) WithPause(pause bool) *RecordingControlParams {
	o.SetPause(pause)
	return o
}

// SetPause adds the pause to the recording control params
func (o *RecordingControlParams) SetPause(pause bool) {
	o.Pause = pause
}

// WriteToRequest writes these params to a swagger request
func (o *RecordingControlParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// query param pause
	qrPause := o.Pause
	qPause := swag.FormatBool(qrPause)
	if qPause != "" {

		if err := r.SetQueryParam("pause", qPause); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
