// Code generated by go-swagger; DO NOT EDIT.

package recorder_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewSetRecordingQualityParams creates a new SetRecordingQualityParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSetRecordingQualityParams() *SetRecordingQualityParams {
	return &SetRecordingQualityParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSetRecordingQualityParamsWithTimeout creates a new SetRecordingQualityParams object
// with the ability to set a timeout on a request.
func NewSetRecordingQualityParamsWithTimeout(timeout time.Duration) *SetRecordingQualityParams {
	return &SetRecordingQualityParams{
		timeout: timeout,
	}
}

// NewSetRecordingQualityParamsWithContext creates a new SetRecordingQualityParams object
// with the ability to set a context for a request.
func NewSetRecordingQualityParamsWithContext(ctx context.Context) *SetRecordingQualityParams {
	return &SetRecordingQualityParams{
		Context: ctx,
	}
}

// NewSetRecordingQualityParamsWithHTTPClient creates a new SetRecordingQualityParams object
// with the ability to set a custom HTTPClient for a request.
func NewSetRecordingQualityParamsWithHTTPClient(client *http.Client) *SetRecordingQualityParams {
	return &SetRecordingQualityParams{
		HTTPClient: client,
	}
}

/*
SetRecordingQualityParams contains all the parameters to send to the API endpoint

	for the set recording quality operation.

	Typically these are written to a http.Request.
*/
type SetRecordingQualityParams struct {

	/* ID.

	   Recording ID
	*/
	ID string

	/* Value.

	   Video quality (value=0 - best quality)
	*/
	Value int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the set recording quality params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetRecordingQualityParams) WithDefaults() *SetRecordingQualityParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the set recording quality params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetRecordingQualityParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the set recording quality params
func (o *SetRecordingQualityParams) WithTimeout(timeout time.Duration) *SetRecordingQualityParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set recording quality params
func (o *SetRecordingQualityParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set recording quality params
func (o *SetRecordingQualityParams) WithContext(ctx context.Context) *SetRecordingQualityParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set recording quality params
func (o *SetRecordingQualityParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set recording quality params
func (o *SetRecordingQualityParams) WithHTTPClient(client *http.Client) *SetRecordingQualityParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set recording quality params
func (o *SetRecordingQualityParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the set recording quality params
func (o *SetRecordingQualityParams) WithID(id string) *SetRecordingQualityParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the set recording quality params
func (o *SetRecordingQualityParams) SetID(id string) {
	o.ID = id
}

// WithValue adds the value to the set recording quality params
func (o *SetRecordingQualityParams) WithValue(value int64) *SetRecordingQualityParams {
	o.SetValue(value)
	return o
}

// SetValue adds the value to the set recording quality params
func (o *SetRecordingQualityParams) SetValue(value int64) {
	o.Value = value
}

// WriteToRequest writes these params to a swagger request
func (o *SetRecordingQualityParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// query param value
	qrValue := o.Value
	qValue := swag.FormatInt64(qrValue)
	if qValue != "" {

		if err := r.SetQueryParam("value", qValue); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
